# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Juan Antonio Breña Moral
email: bren@juanantonio.info
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the personal website of Juan Antonio Breña Moral. 
  his website could be useful for you if you try to learn some stuff 
  about Internet, Robotics & Statistics.
url: "http://www.juanantonio.info" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: juanantoniobm
github_username:  jabrena

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
timezone: GR
encoding: utf-8
permalink: /blog/:year/:month/:day/:title.html



